### Libraries

1. Pandas
2. Numpy
3. matplotlib
4. Scikit-Learn
5. Scipy

In [1]:
#how to draw a line??

In [2]:
#Q. How to create a window??

In [3]:
#Q. What is dataframe??

In [5]:
import pandas as pd
df = pd.read_csv('messages.csv')

In [6]:
print(df)

                  This is message 1 
0          My name is Prabhat Kumar 
1  I am from Mathematics department 


In [12]:
df = pd.read_csv("RAW_DATASET_state_weather_aqi_data.csv")

In [10]:
print(df)

               state               city  \
0     Andhra_Pradesh          Amaravati   
1     Andhra_Pradesh  Rajamahendravaram   
2     Andhra_Pradesh           Tirupati   
3     Andhra_Pradesh      Visakhapatnam   
4     Andhra_Pradesh          Amaravati   
...              ...                ...   
1568     West_Bengal            Kolkata   
1569     West_Bengal            Kolkata   
1570     West_Bengal            Kolkata   
1571     West_Bengal            Kolkata   
1572     West_Bengal           Siliguri   

                                             station        date      time  \
0                     Secretariat, Amaravati - APPCB  03-01-2020  10:00:00   
1     Anand Kala Kshetram, Rajamahendravaram - APPCB  03-01-2020  10:00:00   
2                         Tirumala, Tirupati - APPCB  03-01-2020  10:00:00   
3             GVM Corporation, Visakhapatnam - APPCB  03-01-2020  10:00:00   
4                     Secretariat, Amaravati - APPCB  05-01-2020  06:00:00   
...            

In [14]:
#doubt: How to use usecols??

In [15]:
#numpy

In [16]:
#similar to array but works 50 times faster
#contigous memory locations

In [17]:
import numpy as np

In [19]:
arr = np.array([1,2,3,4,5])

print(id(arr),id(arr[0]))
print(arr.itemsize,arr.strides) #what is strides

1335411653488 1335411584432
4 (4,)


In [20]:
print(type(arr))

<class 'numpy.ndarray'>


In [21]:
print(arr)

[1 2 3 4 5]


In [23]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(id(arr1),id(arr1[0]))
print(arr1.itemsize,arr1.strides)
print(type(arr1))
print(arr1)

1335412030128 1335412024752
4 (20, 4)
<class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
e = np.arange(15).reshape(3,5)
print(c,e,sep = '\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [28]:
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.data)
print(b.ndim, b.shape, b.size, b.dtype, b.itemsize, b.data)
print(c.ndim, c.shape, c.size, c.dtype, c.itemsize, c.data)
print(d.ndim, d.shape, d.size, d.dtype, d.itemsize, d.data)

0 () 1 int32 4 <memory at 0x00000136ECC07920>
1 (5,) 5 int32 4 <memory at 0x00000136ECB3A140>
2 (2, 3) 6 int32 4 <memory at 0x00000136ED2D4450>
3 (2, 2, 3) 12 int32 4 <memory at 0x00000136ED29EC50>


In [35]:
e = np.arange(15).reshape(3, 5)
print(c, e,sep = '\n')

[[1 2 3]
 [4 5 6]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [34]:
print(len(b))
#Printing 1D array
print('\n')
for i in range(len(b)):
    print(b[i])

5


1
2
3
4
5


In [36]:
zeros = np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
#Q. What is the difference between linspace and arange??

In [41]:
from numpy import pi
x = np.linspace(0, 2*pi, 100)
y = np.sin(x)
print(y)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [45]:
a = np.array(([1, 2], [3, 4]))
b = np.array(([1, 2], [3, 4]))
print(a * b)  # Element-wise product
print(a @ b)  # Matrix multiplication

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [43]:
#H.W.: Create two normal list and try to use operator star to multiply the matrices

In [44]:
#* is broadcasting operator

In [46]:
print(np.dot(a, b)) # dot product multiplication
print(a.dot(b)) #dot product

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
